# Gerando Números Aleatórios com NumPy

Importando a Biblioteca NumPy

In [2]:
import numpy as np

#### Gerando um número aleatório da distribuição normal

In [3]:
np.random.normal()

1.2981387866460097

#### Gerando quatro números aleatórios da distribuição normal

In [4]:
np.random.normal(size=4)

array([-0.94162726,  0.73114325,  1.62381952, -1.35767931])

#### Gerando cinco números aleatórios da distribuição uniforme

In [5]:
np.random.uniform(size=5)

array([0.82738022, 0.55919765, 0.01257903, 0.73969161, 0.41448139])

#### Gerando dez números inteiros aleatórios entre 1 e 100

In [6]:
np.random.randint(low=1, high=100, size=10)

array([74, 36, 79, 24, 67, 16, 43, 71, 53, 99])